code-insiders --uninstall-extension dbaeumer.vscode-eslint
code-insiders --uninstall-extension eg2.vscode-npm-script
code-insiders --uninstall-extension Equinusocio.vsc-material-theme
code-insiders --uninstall-extension flowtype.flow-for-vscode
code-insiders --uninstall-extension lonefy.vscode-JS-CSS-HTML-formatter
code-insiders --uninstall-extension lukehoban.Go
code-insiders --uninstall-extension ms-mssql.mssql
code-insiders --uninstall-extension ms-python.python
code-insiders --uninstall-extension ms-vscode.csharp
code-insiders --uninstall-extension ms-vscode.mono-debug
code-insiders --uninstall-extension msjsdiag.debugger-for-chrome
code-insiders --uninstall-extension PeterJausovec.vscode-docker
code-insiders --uninstall-extension PKief.material-icon-theme
code-insiders --uninstall-extension robertohuertasm.vscode-icons
code-insiders --uninstall-extension taichi.react-beautify