version: '3.4'

services:
  bistrofiftytwo.api:
    image: bistrofiftytwo.api
    build:
      context: ./src/BistroFiftyTwo.Api
      dockerfile: Dockerfile
    networks:
      infranet:
        aliases:
          - 'api'
  postgres:
    env_file:
      - ./infrastructure/db/database.env
    restart: 'always'
    ports:
      - '5432:5432'
    build: 
      context: ./infrastructure/db
      dockerfile: Dockerfile
    networks:
      infranet:
        aliases:
          - 'postgres'

networks:
  infranet: