version: '3.4'

services:
  ci-build:
    image: microsoft/dotnet:2.1-sdk
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./BistroFiftyTwo.Linux.sln && dotnet publish ./BistroFiftyTwo.Linux.sln -c Release -o ./obj/Docker/publish"
